version: "3"

services:
  devdb:
    image: postgres:10
    ports:
      - "4444:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"
      - "POSTGRES_DB=db"
  testdb:
    image: postgres:10
    ports:
      - "5555:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"
      - "POSTGRES_DB=db"